# EXAMPLE SECRET FILE - DO NOT COMMIT REAL SECRETS!
# Copy this to secret.yaml and update with your actual values
# OR better yet, use secretGenerator in kustomization.yaml

apiVersion: v1
kind: Secret
metadata:
  name: outalator-db-secret
type: Opaque
stringData:
  username: "outalator"
  password: "changeme"
---
apiVersion: v1
kind: Secret
metadata:
  name: outalator-auth-secret
type: Opaque
stringData:
  client_id: "your-okta-client-id"
  client_secret: "your-okta-client-secret"
  session_key: "generate-a-random-32-byte-key"
